[build]
  command = "ng build"  # Comando para construir la aplicación Angular
  publish = "dist/test-aws/browser"  # Carpeta de salida de Angular donde se encuentran los archivos construidos

[[redirects]]
  from = "/*"  # Redirecciona todas las rutas al index.html
  to = "/index.html"
  status = 200
