[build]
  command = "ng build"  # o "npm run build", según sea necesario
  publish = "dist/test-aws/browser/browser"  # Establecer la ruta correcta para la carpeta de publicación

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200